import React from 'react';
import {
  faMedium,
  faBehanceSquare,
  faReadme,
  faGithubSquare,
  faLinkedin,
  faInstagramSquare
} from '@fortawesome/free-brands-svg-icons';
import { faPenNib, faEnvelope, IconDefinition } from '@fortawesome/free-solid-svg-icons';
// import 'bootstrap-icons';

export const menuItems = [
  { text: 'Graphic Design', path: '/designs', icon: faPenNib },
  { text: 'Code Tutorials', path: '/blog', icon: faReadme }
];

export const accounts: Record<string, Account> = {
  email: {
    name: 'Email',
    username: 'gwgraphicdesign@gmail.com',
    link: 'mailto:gwgraphicdesign@gmail.com',
    icon: <svg src="../../node_modules/bootstrap-icons/icons/envelope.svg" width="32" height="32" title="Bootstrap" />
  },
  github: {
    name: 'Github',
    username: 'glweems',
    link: 'https://github.com/glweems',
    icon: faGithubSquare
  },
  linkedin: {
    name: 'LinkedIn',
    username: 'glweems',
    link: 'https://www.linkedin.com/in/glweems',
    icon: faLinkedin
  },
  medium: {
    name: 'Medium',
    username: 'glweems',
    link: 'https://medium.com/@glweems',
    icon: faMedium
  },
  behance: {
    name: 'Behance',
    username: 'glweems',
    link: 'https://www.behance.net/glweems',
    icon: faBehanceSquare
  },
  instagram: {
    name: 'Instagram',
    username: 'glweems',
    link: 'https://instagram.com/glweems',
    icon: faInstagramSquare
  }
};

export default { menuItems, accounts };

// Generated by https://quicktype.io
interface Account {
  name: string;
  username: string;
  link: string;
  icon: IconDefinition | React.ReactNode;
}
